### ISSUE TITLE
ImportError: No module named _camfr

### ISSUE THREAD

**Issue by bernardyeszero** [demisjohn/CAMFR#17]
Dear demusjohn,

Thanks for your contribution to camfr maintenance. I installed camfr on my Macbook Pro, with "python setup.py install".
 I created a virtual  py27 environment using conda and changed the paths in "machine_cfg.py". Then it seems the installation is successful and the output is as follows:

running install
running build
scons: Reading SConscript files ...

scons: warning: The env.Copy() method is deprecated; use the env.Clone() method instead.
File "/Users/lrunze/Desktop/temp/CAMFR-master/SConstruct", line 19, in <module>
scons: done reading SConscript files.
scons: Building targets ...
scons: `camfr' is up to date.
scons: done building targets.
running build_py
running install_lib
running install_data
copying camfr/_camfr.dylib -> /Users/lrunze/anaconda3/envs/camfr/lib/python2.7/site-packages/camfr/.
error: can't copy 'docs/camfr.pdf': doesn't exist or not a regular file

The camfr.pdf is not so vital. But when I run the example file "Silicon-Waveguide...", there is an error message:

ImportError: No module named _camfr

I have no idea to address this. Could you please some suggestion?

BTW. Here is my file tree in "*/site-packages/camfr/":

![image](https://user-images.githubusercontent.com/13745165/63458667-c8332400-c485-11e9-8553-a60b119d360c.png)

Thanks!

**Comment by demisjohn** [comment]
Solution is in issue #7:
https://github.com/demisjohn/CAMFR/issues/7

Rename `_camfr.dylib` to `_camfr.so` And it should work.
