### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ValeriiaSedova** [demisjohn/CAMFR#18]
Hello! I tried to built Camfr for Windows 10 but failed. In the end, I downloaded .exe file from that source [](https://sourceforge.net/projects/camfr/). It worked eventually but I have some issues with the plotting. I could not get the same results as in 

> examples/contrib/Example - Silicon-Waveguide ModeSim v2018-01.py

the Section.plot() does not seem to be there.
I think, that is because the link has different version of Camfr. Can you, please, give an instruction how to download it on Windows with upgraded version of Camfr? Many thanks!

![image](https://user-images.githubusercontent.com/64003586/95705408-2572d180-0c54-11eb-9a3b-0b0bc29262cd.png)

**Comment by ammaster** [comment]
Hi Valeria, did you just simply run the exe on Win10? Did you do something special? Are you using Anaconda with a Python 2.X environment?

**Comment by demisjohn** [comment]
It sounds like you might have run the Example script from this CAMFR fork, but with a CAMFR installation that you got somewhere else. I don’t remember there being a pre-built windows .Exe in this repo. 

The ‘Section.plot()’ method will not exist on other CAMFR installations unless they were derived from this fork. As far as I know, this is the only fork to implement MatPlotLib plotting. 

What were the build problems you ran into while building this fork on your computer?
I updated the INSTALL.MacOS read me file to explain how to get this working on MacOS - I didn’t try figuring out the dependencies on Windows. But if you can post your build errors perhaps we can help.

**Comment by demisjohn** [comment]
Now that I think about it, a pre-built windows .EXE is likely a virus from some random website - don't run it!!  Download the original source and compile from a GitHub fork.
