### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PedroOliviera** [demisjohn/CAMFR#19]
How do I install this package? In the readme it says to, "see the 'releases' or 'tags' section of this github repo" but on GitHub it says "no releases published"? Thank you for any help you can provide me. (I understand there is no working version for python 3.x)

**Comment by demisjohn** [comment]
Try this button, in the (CODE) dropdown:
<img width="855" alt="Untitled 2" src="https://user-images.githubusercontent.com/5370181/158737775-6640965a-cb82-46f8-9d1c-43f9b4c1f5cd.png">

**Comment by PedroOliviera** [comment]
Thanks! Sorry for the dumb question.

The problem I am having now is that I am trying to install the module by running "python setup.py install" but the command prompt says there is "No module named machine_cfg". Do you have a suggested way for installing this module?
